obj_player.shotgunAnim = 1;
instance_destroy();
global.ammo = 15;
obj_player.state = 24;
obj_player.sprite_index = spr_shotgun_pullout;
obj_player.mach2 = 0;
obj_player.movespeed = 0;
obj_player.hsp = 0;
obj_player.image_index = 0;
obj_tv.showtext = 1;
obj_tv.message = "ITS TIME TO CHEW ASS";
obj_tv.tvsprite = spr_tvdook;
obj_tv.alarm[0] = 150;
obj_tv.image_speed = 0.1;