instance_create((x + 32), (y + 32), obj_debris);
instance_create((x + 32), (y + 32), obj_debris);
instance_create((x + 32), (y + 32), obj_debris);
instance_create((x + 32), (y + 32), obj_debris);
instance_create((x + 32), (y + 32), obj_debris);
instance_create((x + 32), (y + 32), obj_debris);
instance_create((x + 32), (y + 32), obj_debris);
instance_create((x + 32), (y + 32), obj_debris);
tile_layer_delete_at(1, x, y);
scr_sound(sound_hit);